# Generated by Django 4.2 on 2023-08-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_id', models.IntegerField(unique=True)),
                ('current_floor', models.IntegerField(default=1)),
                ('destination_floor', models.IntegerField(default=1)),
                ('direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('STOP', 'Stop')], default='STOP', max_length=10)),
                ('is_operational', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], max_length=10)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.elevator')),
            ],
        ),
    ]
